### PR TITLE
refactor(opam-switch--get-switches): Use command `opam switch -s`

### LINKED ISSUE #15: (opam-switch--get-switches) could use `opam switch -s`
cf.
https://github.com/ProofGeneral/opam-switch-mode/blob/d095d0ee6e6df9e312330e03cf3d719e4da6d0d9/opam-switch-mode.el#L186

### PR DESCRIPTION
**Pull request by erikmd**
so we avoid regexp filtering code.

Close #15

Cc @monnier: does this simplification look good to you?

### CODE REVIEW

**Comment by monnier** [comment]
> Cc @monnier: does this simplification look good to you?

Nice, yes.  Can we signal an error if we don't get a 0 output rather
than throwing it away silently?

**Comment by erikmd** [comment]
Dear @monnier,
I'm not sure I got your suggestion:
the current code already signals an error:

```elisp
(defun opam-switch--get-switches ()
  "Return all opam switches as list of strings."
  (with-temp-buffer
    (unless
        (eq (opam-switch--run-command-without-stderr "switch" nil nil "-s") 0)
      ;; option -s means --short
      ;; opam exit status different from 0 implies some error occured
      (error "Command 'opam switch' failed"))
    (split-string (buffer-string) "\n" t)))
```

but maybe I misunderstood.

**Comment by erikmd** [comment]
Anyway, (opam-switch--get-switches) already calls (opam-switch--run-command-without-stderr) which calls opam, which errors if opam is not found, e.g. I did this testing:

```
$ sudo mv $(which opam){,~}  # to temporarily remove opam from the PATH
M-: (setq debug-on-error t)
M-x opam-switch-set-switch
```
and got
```
Debugger entered--Lisp error: (file-missing "Searching for program" "No such file or directory" "opam")
  call-process("opam" nil (t nil) nil "env" "--sexp" "--set-switch" "--switch=/home/emartin/forge/git/bot")
  apply(call-process "opam" nil (t nil) nil ("env" "--sexp" "--set-switch" "--switch=/home/emartin/forge/git/bot"))
  process-file("opam" nil (t nil) nil "env" "--sexp" "--set-switch" "--switch=/home/emartin/forge/git/bot")
  apply(process-file "opam" nil (t nil) nil "env" ("--sexp" "--set-switch" "--switch=/home/emartin/forge/git/bot"))
  (let ((process-environment (append opam-switch-common-environment process-environment)) (options (append args opam-switch-common-options))) (if switch (progn (setq options (cons (format "--switch=%s" switch) options)) (setq options (cons "--set-switch" options)))) (if sexp (progn (setq options (cons "--sexp" options)))) (apply #'process-file opam-switch-program-name nil '(t nil) nil sub-cmd options))
  opam-switch--run-command-without-stderr("env" "/home/emartin/forge/git/bot" t)
  apply(opam-switch--run-command-without-stderr "env" "/home/emartin/forge/git/bot" t nil)
  (let ((status (apply #'opam-switch--run-command-without-stderr sub-cmd switch sexp args))) (if (eq status 0) (buffer-string) nil))
  (progn (let ((status (apply #'opam-switch--run-command-without-stderr sub-cmd switch sexp args))) (if (eq status 0) (buffer-string) nil)))
  (unwind-protect (progn (let ((status (apply #'opam-switch--run-command-without-stderr sub-cmd switch sexp args))) (if (eq status 0) (buffer-string) nil))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (let ((status (apply #'opam-switch--run-command-without-stderr sub-cmd switch sexp args))) (if (eq status 0) (buffer-string) nil))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (let ((status (apply ... sub-cmd switch sexp args))) (if (eq status 0) (buffer-string) nil))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))
  opam-switch--command-as-string("env" "/home/emartin/forge/git/bot" t)
  (let ((output-string (opam-switch--command-as-string "env" switch-name t)) (prefix (opam-switch--get-current-switch-prefix)) opam-env) (if output-string nil (error "Command 'opam env --switch=%s --set-switch' failed..." switch-name switch-name)) (setq opam-env (car (read-from-string output-string))) (if opam-switch--saved-env nil (opam-switch--save-current-env opam-env)) (opam-switch--set-env opam-env prefix))
  (if (equal switch-name "") (opam-switch--reset-env) (let ((output-string (opam-switch--command-as-string "env" switch-name t)) (prefix (opam-switch--get-current-switch-prefix)) opam-env) (if output-string nil (error "Command 'opam env --switch=%s --set-switch' failed..." switch-name switch-name)) (setq opam-env (car (read-from-string output-string))) (if opam-switch--saved-env nil (opam-switch--save-current-env opam-env)) (opam-switch--set-env opam-env prefix)))
  opam-switch-set-switch("/home/emartin/forge/git/bot")
```

but beyond that, it's difficult to test the case where `opam` is found but returns a nonzero exit status.

After saying all this, are you in favor of merging this patch?

**Comment by monnier** [comment]
> I'm not sure I got your suggestion:

Hmm... sorry, brain fart.

**Comment by erikmd** [comment]
No worries @monnier !-) So, merged now.

**Pull request merged**
